# Site settings
title: Mihir Samant
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Mihir Samant
user_description: I'm a Senior Data Analyst from Canada, always searching for the next challenge.Proactive, result-oriented, technically qualified, Master of Applied Computing with 6+ years of Data Analytics experience. Progressive experience of three years in Python and Data Warehouses like Big Query, Redshift, Microsoft Azure, Snowflake. Ability to create meaningful insights from raw data by applying ETL and ELT tools like Apache Airflow, SSIS. Experience of creating dashboards for wide range of data using BI tools such as Tableau, PowerBI and Looker.
user_title: Data Analyst
email: mihirs202@gmail.com
# twitter_username: 
# instagram_username: 
# facebook_username: 
linkedin_username: misamant
github_username:  misamant
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']