# Site settings
title: Mihir Samant
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Mihir Samant
user_description: As a seasoned Senior Data Analyst hailing from Canada, I'm continuously on the lookout for the next stimulating challenge. With a proactive and results-oriented approach, I bring a wealth of technical expertise to the table, holding a Master of Applied Computing degree and boasting over 6 years of hands-on experience in the realm of Data Analytics. Over the course of my career, I've honed my skills across various domains, with a particular focus on Python programming and navigating Data Warehouses such as Big Query, Redshift, Microsoft Azure, and Snowflake. My proficiency extends beyond mere data manipulation; I excel in extracting meaningful insights from raw datasets, leveraging a blend of ETL and ELT tools including Apache Airflow and SSIS. Moreover, my repertoire includes crafting dynamic dashboards that breathe life into diverse datasets. I'm adept at utilizing leading BI tools like Tableau, PowerBI, and Looker to transform intricate data sets into actionable insights that drive informed decision-making.
user_title: Data Professional
email: mihirs202@gmail.com
# instagram_username: 
# facebook_username: 
linkedin_username: misamant
github_username:  miSamant
tableau_username: mihir5633
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

work_exprience: As a seasoned Senior Data Analyst based in Canada, I'm always on the lookout for my next stimulating challenge. With 7+ years of experience in the IT industry, I’ve worked across diverse domains including Insurance, Non-Profits, FinTech, and Finance. Throughout my journey, I’ve consistently embraced a learner’s mindset—adapting to emerging trends and continuously upskilling.
Beyond analysis, I’ve led several end-to-end data initiatives, from defining KPIs and building pipelines to architecting scalable data solutions. One of my most rewarding experiences was building a data team from the ground up—hiring, mentoring, and establishing team workflows that aligned with business goals. I’ve also played a key role in designing robust data architectures that ensured efficient data access, governance, and reporting across departments. I thrive in collaborative environments where I can combine technical depth with leadership to deliver high-impact, data-driven outcomes.
