# Site settings
title: Mihir Samant
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Mihir Samant
user_description: As a seasoned Senior Data Analyst hailing from Canada, I'm continuously on the lookout for the next stimulating challenge. With a proactive and results-oriented approach, I bring a wealth of technical expertise to the table, holding a Master of Applied Computing degree and boasting over 6 years of hands-on experience in the realm of Data Analytics. Over the course of my career, I've honed my skills across various domains, with a particular focus on Python programming and navigating Data Warehouses such as Big Query, Redshift, Microsoft Azure, and Snowflake. My proficiency extends beyond mere data manipulation; I excel in extracting meaningful insights from raw datasets, leveraging a blend of ETL and ELT tools including Apache Airflow and SSIS. Moreover, my repertoire includes crafting dynamic dashboards that breathe life into diverse datasets. I'm adept at utilizing leading BI tools like Tableau, PowerBI, and Looker to transform intricate data sets into actionable insights that drive informed decision-making.
user_title: Data Analyst
email: mihirs202@gmail.com
twitter_username: Mihirs202
# instagram_username: 
# facebook_username: 
linkedin_username: misamant
github_username:  miSamant
tableau_username: mihir5633
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']